package vault

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateTemplate reads the encrypted .env file and produces a .env.template
// file with all keys present but values replaced by empty strings or
// optional placeholder comments describing each key.
func GenerateTemplate(cfg Config, dst string) (string, error) {
	if !IsInitialised(cfg) {
		return "", fmt.Errorf("vault is not initialised; run 'envault init' first")
	}

	if _, err := os.Stat(cfg.EncryptedFile); os.IsNotExist(err) {
		return "", fmt.Errorf("encrypted file not found: %s", cfg.EncryptedFile)
	}

	identity, err := loadVaultIdentity(cfg)
	if err != nil {
		return "", fmt.Errorf("load identity: %w", err)
	}

	envMap, err := decryptToMap(cfg.EncryptedFile, identity)
	if err != nil {
		return "", fmt.Errorf("decrypt env file: %w", err)
	}

	if dst == "" {
		dst = filepath.Join(filepath.Dir(cfg.PlainFile), ".env.template")
	}

	var sb strings.Builder
	sb.WriteString("# Generated by envault — do not commit real secrets\n")
	sb.WriteString("# Fill in values before use\n\n")

	for key := range envMap {
		sb.WriteString(key)
		sb.WriteString("=\n")
	}

	if err := os.WriteFile(dst, []byte(sb.String()), 0o644); err != nil {
		return "", fmt.Errorf("write template file: %w", err)
	}

	return dst, nil
}
